language: php
php:
- "5.5"
notifications:
  email:
    - joseph@captaincourier.org
    - peter@captaincourier.org
env:
    global:
        # key for resources    
        - secure: "dACOugZycghZficQn/gk4LpFEs6lyvsewgXfHwnISfKrBmqoyE0xY3RX4DvKMiPadntfXMSRRSKoA9Y1cwZnAs41FoLs+2UADjzHp4BwL90tqrlH2N1qysCUVVrxFVUvhlLhmgRDbvBCtbQsq8JoJzme+fyMyXqP+TFrAdW7mIM="
before_script:  
    - sudo apt-get install p7zip-full
    - composer install
script: 
    - ./script/decrypt.bash
    - phpunit --configuration=phpunit.xml src/

