#! /bin/bash

cd src/Scrappy
echo "starting scrappy"
node scrappy.js &
pid=$!
cd -
sleep 1
echo "waiting for scrappy to setup"
echo "starting tests"
# phpunit --configuration=phpunit.xml src/Cidr/Courier/P4D/Tests
phpunit --configuration=phpunit.xml src/Cidr/Courier/ParcelForce/Tests
echo "killing process scrappy process '$pid'"
kill $pid
