parameters:
    p4dApiUrl: https://www.p4d.co.uk/p4d/api/v2
    p4dName: P4D
services:

    p4dCreateShipment:
        class: Cidr\Courier\P4D\CreateShipment
        scope: prototype        
        arguments:
            - '%p4dApiUrl%'
            - '%p4dname%'
            - '@curl'
            - '@p4dGetQuote'
            - '@shipmentIdGenerator'
        tags:
            - { name: cidr_capability }

    p4dGetQuote:
        class: Cidr\Courier\P4D\GetQuote
        scope: prototype
        arguments:
            - "%p4dName%"
            - "%p4dApiUrl%"
            - "@curl"
            - "@cidrResponseFactory"
            - "@cidrResponseContextGetQuoteFactory"
        tags:
            - { name: cidr_capability }

    p4dPrintLabel:
        class: Cidr\Courier\P4D\PrintLabel
        scope: prototype
        arguments:
            - "%p4dApiUrl%"
            - "%p4dName%"

        tags:
            - { name: cidr_capability }
